name: Automated Comment Bot

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on bug issues
        if: contains(github.event.issue.labels.*.name, 'bug')
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "Thank you. We will fix it. Best regards, Karthik Abinav Sankararaman."
      - name: Comment on feature issues
        if: contains(github.event.issue.labels.*.name, 'feature')
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "Thank you, we will consider to include this feature. Best regards, Karthik Abinav Sankararaman."
      - name: Comment on discussion issues
        if: contains(github.event.issue.labels.*.name, 'discussion')
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "Happy to discuss this topic with you. Best regards, Karthik Abinav Sankararaman."
