name: Issue Auto Comment Bot
on:
  issues:
    types: [opened]
permissions:
  issues: write
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on bug
        if: contains(github.event.issue.labels.*.name, 'bug')
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "Thank you. We will fix it. Best regards, karthikabinav."
      - name: Comment on feature
        if: contains(github.event.issue.labels.*.name, 'feature')
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "Thank you, we will consider to include this feature. Best regards, karthikabinav."
      - name: Comment on discussion
        if: contains(github.event.issue.labels.*.name, 'discussion')
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "Happy to discuss this topic with you. Best regards, karthikabinav."
